# Use a trusted server. This should be a stratum-1 server that we fully control
# time.brics4d.com is a stratum 1 (or alias) time server
# As of 2025-05-10, this server is located in Providence, RI, USA
server time.brics4d.com iburst prefer

# This directive specify the location of the file containing ID/key pairs for
# NTP authentication.
keyfile /etc/chrony/chrony.keys

# This directive specify the file into which chronyd will store the rate
# information.
driftfile /var/lib/chrony/chrony.drift

# Save NTS keys and cookies.
ntsdumpdir /var/lib/chrony

# Uncomment the following line to turn logging on.
log tracking measurements statistics

# Log files location.
logdir /var/log/chrony

# Stop bad estimates upsetting machine clock.
maxupdateskew 100.0

# Step the system clock instead of slewing it if the adjustment is larger than
# one second, but only in the first four clock updates.
makestep 1 4

# This directive enables kernel synchronisation (every 11 minutes) of the
# real-time clock. Note that it can’t be used along with the 'rtcfile' directiv>
#rtcsync